### ISSUE TITLE
cannot open resource - Nvidia Python 3.12 in linux

### ISSUE THREAD

**Issue by Milor123** [prodogape/ComfyUI-EasyOCR#5]
Hi guys, i am trying running it with a simple small image of english text

![image](https://github.com/user-attachments/assets/baaea91e-8830-4cd8-8604-57d9be3f198d)

neither work using the other option:
![image](https://github.com/user-attachments/assets/7eecc4e5-ee56-43d9-b057-60159bcfd57e)

checking the logs i see it says `OSError: cannot open resource` , could be it a error related with linux?

ComfyUi Error output:

```
Error occurred when executing Apply EasyOCR:

cannot open resource

File "/home/noe/Documentos/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/noe/Documentos/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/noe/Documentos/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/noe/Documentos/ComfyUI/custom_nodes/ComfyUI-EasyOCR/node.py", line 243, in main
image_tensor, mask_tensor, labelme_data = plot_boxes_to_image(image_pil, pred_dict)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/noe/Documentos/ComfyUI/custom_nodes/ComfyUI-EasyOCR/node.py", line 109, in plot_boxes_to_image
font = ImageFont.truetype(font_path, font_size)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/noe/.pyenv/versions/3.12.1/envs/Comfyv4_312/lib/python3.12/site-packages/PIL/ImageFont.py", line 807, in truetype
return freetype(font)
^^^^^^^^^^^^^^
File "/home/noe/.pyenv/versions/3.12.1/envs/Comfyv4_312/lib/python3.12/site-packages/PIL/ImageFont.py", line 804, in freetype
return FreeTypeFont(font, size, index, encoding, layout_engine)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/noe/.pyenv/versions/3.12.1/envs/Comfyv4_312/lib/python3.12/site-packages/PIL/ImageFont.py", line 244, in __init__
self.font = core.getfont(
^^^^^^^^^^^^^
```

Python console error output when try run the it.
```
No pending upload
got prompt
Failed to validate prompt for output 12:
* (prompt):
  - Required input is missing: text
* ShowText|pysssss 12:
  - Required input is missing: text
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! cannot open resource
Traceback (most recent call last):
  File "/home/noe/Documentos/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/Documentos/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/Documentos/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/Documentos/ComfyUI/custom_nodes/ComfyUI-EasyOCR/node.py", line 243, in main
    image_tensor, mask_tensor, labelme_data = plot_boxes_to_image(image_pil, pred_dict)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/Documentos/ComfyUI/custom_nodes/ComfyUI-EasyOCR/node.py", line 109, in plot_boxes_to_image
    font = ImageFont.truetype(font_path, font_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.12.1/envs/Comfyv4_312/lib/python3.12/site-packages/PIL/ImageFont.py", line 807, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.12.1/envs/Comfyv4_312/lib/python3.12/site-packages/PIL/ImageFont.py", line 804, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.12.1/envs/Comfyv4_312/lib/python3.12/site-packages/PIL/ImageFont.py", line 244, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource

Prompt executed in 1.27 seconds
No pending uploa
```

**Comment by MIOleaf77** [comment]
tyr to insert one space between pingfang and regular in the filename which is comfyui/comfyui_nodes/docs/pingfangregular.ttf

**Comment by ryzen88** [comment]
I have the same issue on windows, unfortunately adding a space between it does not work.

**Comment by maxpaynestory** [comment]
Open comfyui folder comfyui\ComfyUI\custom_nodes\ComfyUI-EasyOCR\docs

make a copy of file PingFangRegular.ttf

rename the new copied file to

PingFang Regular.ttf

that will fix the issue

**Comment by MikeTheSnowman** [comment]
> Open comfyui folder comfyui\ComfyUI\custom_nodes\ComfyUI-EasyOCR\docs
> 
> make a copy of file PingFangRegular.ttf
> 
> rename the new copied file to
> 
> PingFang Regular.ttf
> 
> that will fix the issue

I have a similar setup on windows and can confirm that this worked for me. Thanks!

**Comment by Lilien86** [comment]
I copied the file and made an copy but I have always the same error "cannot open resource". I'm based on Windows 11 with RTX 4070

**Comment by weirenjie3** [comment]
> Open comfyui folder comfyui\ComfyUI\custom_nodes\ComfyUI-EasyOCR\docs
> 
> make a copy of file PingFangRegular.ttf
> 
> rename the new copied file to
> 
> PingFang Regular.ttf
> 
> that will fix the issue

太nb了,这有效果
